# Generated by Django 5.0.2 on 2024-02-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('rc_book_radio', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('rc_book_image', models.ImageField(blank=True, null=True, upload_to='rc_book_images/')),
                ('previous_policy_radio', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('previous_policy_image', models.ImageField(blank=True, null=True, upload_to='previous_policy_images/')),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
