# Generated by Django 5.0.2 on 2024-02-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_insuranceenquiry_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('rc_book_radio', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
                ('rc_book_image', models.ImageField(blank=True, null=True, upload_to='rc_book_images/')),
                ('documents', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
    ]
