# Generated by Django 5.0.2 on 2024-03-01 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_document_remove_loanenquiry_documents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=59, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=42)),
            ],
        ),
    ]
