# Generated by Django 5.0.2 on 2024-03-04 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='rc_book',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
