# Generated by Django 5.0.2 on 2024-03-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_loan_rc_book_loan_rc_book_radio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='rc_book_radio',
        ),
        migrations.AddField(
            model_name='loan',
            name='rc_book',
            field=models.BooleanField(default=False),
        ),
    ]
