# Generated by Django 5.0.2 on 2024-03-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_loan_rc_book_radio_loan_rc_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyissue',
            options={'ordering': ['date', 'name', 'number', 'ckyc', 'p_number', 'v_number', 'Vehicle', 'c_number', 'e_number', 'Location', 'HP_bank', 'business_type', 'insurance_type', 'insurance_portal', 'I_company', 'payment', 'payment_sos', 'PS_date', 'PE_date', 'Ncb', 'Premium', 'odNetPremium', 'commissionPercentage', 'payoutDiscount', 'PayoutAmount', 'profitResult', 'tdsPercentage', 'profitAfterTDSResult', 'netProfitResult', 'Executive', 'DSA']},
        ),
        migrations.AddField(
            model_name='policyissue',
            name='ckyc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
