# Generated by Django 5.0.2 on 2024-03-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_policyissue_options_policyissue_ckyc'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='remarks',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
