# Generated by Django 5.0.2 on 2024-03-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_loan_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
