# Generated by Django 5.0.2 on 2024-03-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_users_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
